/** Pro: export a shareable report. The free tier prints to stdout (cli.ts);
 *  file export is the licensed feature, gated by requirePro.
 *
 *  Two formats, one content model: Markdown (paste into a PR / README) and a
 *  standalone HTML document (share a link / open in a browser). Both render the
 *  same LintResult, so a report never disagrees with the CLI.
 *
 *  Untrusted-input note: tool names, descriptions and rule messages originate
 *  from arbitrary third-party MCP JSON — the linter's whole job is parsing
 *  servers we don't control. Markdown escapes table pipes; HTML escapes the
 *  five HTML-significant characters so the report can never inject markup into
 *  the browser that opens it. */
import type { Finding, LintResult } from "../core/types.js";

export type ReportFormat = "md" | "html";

const DISCLAIMER =
  "Generated by mcplint. Automated linting catches structure and hygiene, not intent — review findings in context.";

export function toMarkdown(result: LintResult, source: string): string {
  const { score, toolCount, counts, estimatedTokens, findings } = result;
  const lines: string[] = [
    `# mcplint report — ${source}`,
    "",
    `**Score: ${score}/100**  ·  ${toolCount} tools  ·  ~${estimatedTokens} context tokens`,
    "",
    `Errors: ${counts.error} · Warnings: ${counts.warning} · Info: ${counts.info}`,
    "",
  ];
  if (findings.length === 0) {
    lines.push("No issues found.");
  } else {
    lines.push("| Severity | Tool | Rule | Message |", "|---|---|---|---|");
    for (const f of findings) {
      lines.push(`| ${f.severity} | ${f.tool ?? "—"} | ${f.ruleId} | ${escapePipes(f.message)} |`);
    }
  }
  lines.push("", `_${DISCLAIMER}_`, "");
  return lines.join("\n");
}

/** A standalone, self-contained HTML report — inlined CSS, no external assets,
 *  fonts or scripts, so it works offline and opens straight from disk. */
export function toHtml(result: LintResult, source: string): string {
  const { score, toolCount, counts, estimatedTokens, findings } = result;
  const band = scoreBand(score);

  const body =
    findings.length === 0
      ? `<p class="ok">No issues found.</p>`
      : `<table>
      <thead><tr><th>Severity</th><th>Tool</th><th>Rule</th><th>Message</th></tr></thead>
      <tbody>
${findings.map(findingRow).join("\n")}
      </tbody>
    </table>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>mcplint report — ${esc(source)}</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    font: 15px/1.55 ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
    margin: 0; padding: 2.5rem 1.25rem; color: #1a1d21; background: #f5f6f8;
  }
  main { max-width: 880px; margin: 0 auto; }
  h1 { font-size: 1.25rem; font-weight: 650; margin: 0 0 .25rem; }
  .source { color: #6b7280; font-size: .85rem; word-break: break-all; margin: 0 0 1.75rem; }
  .scorecard {
    display: flex; align-items: center; gap: 1.5rem; flex-wrap: wrap;
    background: #fff; border: 1px solid #e3e6ea; border-radius: 14px;
    padding: 1.5rem 1.75rem; margin-bottom: 1.5rem;
  }
  .score { font-size: 3rem; font-weight: 700; line-height: 1; }
  .score.good { color: #1a7f37; } .score.warn { color: #b7791f; } .score.bad { color: #c2362f; }
  .score small { font-size: 1rem; font-weight: 500; color: #9aa0a6; }
  .meta { display: flex; gap: 1.75rem; flex-wrap: wrap; }
  .meta div { display: flex; flex-direction: column; }
  .meta b { font-size: 1.35rem; font-weight: 650; }
  .meta span { font-size: .78rem; color: #6b7280; text-transform: uppercase; letter-spacing: .04em; }
  table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e3e6ea; border-radius: 14px; overflow: hidden; }
  th, td { text-align: left; padding: .7rem .9rem; border-bottom: 1px solid #eef0f3; vertical-align: top; }
  th { font-size: .74rem; text-transform: uppercase; letter-spacing: .04em; color: #6b7280; background: #fafbfc; }
  tr:last-child td { border-bottom: 0; }
  td.tool, td.rule { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .85rem; white-space: nowrap; }
  .sev { font-size: .72rem; font-weight: 650; text-transform: uppercase; letter-spacing: .03em; padding: .1rem .45rem; border-radius: 999px; }
  .sev.error { color: #c2362f; background: #fbe9e7; }
  .sev.warning { color: #b7791f; background: #fdf3df; }
  .sev.info { color: #1f6feb; background: #e7f0fe; }
  .ok { background: #fff; border: 1px solid #e3e6ea; border-radius: 14px; padding: 1.5rem; color: #1a7f37; font-weight: 600; }
  footer { color: #9aa0a6; font-size: .8rem; margin-top: 1.5rem; }
  @media (prefers-color-scheme: dark) {
    body { color: #e6e8eb; background: #15171a; }
    .scorecard, table, .ok { background: #1d2024; border-color: #2c3036; }
    th { background: #232730; color: #9aa0a6; }
    th, td { border-color: #2c3036; }
    .source, footer { color: #8b9096; }
  }
</style>
</head>
<body>
<main>
  <h1>mcplint report</h1>
  <p class="source">${esc(source)}</p>
  <section class="scorecard">
    <div class="score ${band}">${score}<small>/100</small></div>
    <div class="meta">
      <div><b>${toolCount}</b><span>tools</span></div>
      <div><b>~${estimatedTokens}</b><span>context tokens</span></div>
      <div><b>${counts.error}</b><span>errors</span></div>
      <div><b>${counts.warning}</b><span>warnings</span></div>
      <div><b>${counts.info}</b><span>info</span></div>
    </div>
  </section>
  ${body}
  <footer>${esc(DISCLAIMER)}</footer>
</main>
</body>
</html>
`;
}

function findingRow(f: Finding): string {
  return `        <tr><td><span class="sev ${f.severity}">${f.severity}</span></td><td class="tool">${esc(f.tool ?? "—")}</td><td class="rule">${esc(f.ruleId)}</td><td>${esc(f.message)}</td></tr>`;
}

function scoreBand(score: number): "good" | "warn" | "bad" {
  if (score >= 90) return "good";
  if (score >= 70) return "warn";
  return "bad";
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}

/** Escape the five HTML-significant characters. Applied to every piece of
 *  untrusted tool data before it reaches the document. */
function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
