/** Pro: export a shareable Markdown report. The free tier prints to stdout
 *  (cli.ts); file export is the licensed feature, gated by requirePro. */
import type { LintResult } from "../core/types.js";

export function toMarkdown(result: LintResult, source: string): string {
  const { score, toolCount, counts, estimatedTokens, findings } = result;
  const lines: string[] = [
    `# mcplint report — ${source}`,
    "",
    `**Score: ${score}/100**  ·  ${toolCount} tools  ·  ~${estimatedTokens} context tokens`,
    "",
    `Errors: ${counts.error} · Warnings: ${counts.warning} · Info: ${counts.info}`,
    "",
  ];
  if (findings.length === 0) {
    lines.push("No issues found.");
  } else {
    lines.push("| Severity | Tool | Rule | Message |", "|---|---|---|---|");
    for (const f of findings) {
      lines.push(`| ${f.severity} | ${f.tool ?? "—"} | ${f.ruleId} | ${escapePipes(f.message)} |`);
    }
  }
  lines.push(
    "",
    "_Generated by mcplint. Automated linting catches structure and hygiene, not intent — review findings in context._",
    "",
  );
  return lines.join("\n");
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}
